apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    env: dev
spec:
  containers:
    - name: nginx-ctr
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
    - name: busybox-ctr
      image: busybox
      command:
        - sleep
        - "3600"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 81   
